app:
  title: "Invoice Reader"
  description: "Upload an invoice (PDF, image, or text) or enter invoice text directly to generate a summary."
  supported_files:
    - pdf
    - png
    - jpg
    - jpeg
    - svg
    - txt

openai:
  model: "gpt-4o"
  temperature: 0.1
  max_tokens_summary: 2000
  max_tokens_image_analysis: 2000
  system_role_summary: "You are an AI assistant that specializes in extracting and summarizing invoice information."
  system_role_image: "You are an AI assistant that specializes in extracting text from invoice images and organizing the information."